import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { getDeliveries, getDelivery, createDelivery, signDelivery, updateDeliveryStatus } from '../controllers/deliveriesController';
const router = Router();
router.use(authenticate);
router.get('/', getDeliveries);
router.get('/:id', getDelivery);
router.post('/', createDelivery);
router.patch('/:id/sign', signDelivery);
router.patch('/:id/status', updateDeliveryStatus);
export default router;
