import { Router } from 'express';
import { authenticate } from '../middleware/auth';
import { getInvoices, getInvoice, createInvoice, addPayment, getInvoiceSummary } from '../controllers/invoicesController';
const router = Router();
router.use(authenticate);
router.get('/summary', getInvoiceSummary);
router.get('/', getInvoices);
router.get('/:id', getInvoice);
router.post('/', createInvoice);
router.post('/:id/payments', addPayment);
export default router;
